# Generated by Django 4.1.5 on 2023-02-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_author_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_set', to='quotes.author'),
        ),
    ]
