name: Test RESTless API

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - name: Install Setup
        run: make setup

      - name: Start application locally
        run: |
          make serve-bg
          sleep 5

      - name: Run tests
        run: pytest -vk test_unauth

      - name: Stop background process
        run: kill $(lsof -t -i:8000)
